# 实验环境: ivankastage
# 实验目的: 验证hostNetwork字段
# 用途: 可利用此字段意义在各个宿主机上安装对应的exporter, 利用{nodeIP}:{containerPort}来采集宿主机数据。比如见闻正在用的node-exporter
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ds
  namespace: default
spec:
  revisionHistoryLimit: 3
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
        - name: nginx
          image: nginx