#尝试创建local pv
#local 对比 hostPath增加了 nodeAffinity字段。使用此pvc的调度时会收到次字段影响。
#好处是pod在创建时就不必关系affinity问题了。
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    usage: test
spec:
  cacpcity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/pvdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              value: 10.0.0.5

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: default
spec:
  resources:
    requests: 5Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      usage: test
  storageClassName: local


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
        - name: local-pvc
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: local-pvc
              mountPath: /opt/data



